### ISSUE TITLE
Genome Browser: Closing a channel causes a dramatic error.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#1132]
_From @leehart on July 30, 2018 15:10_

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button]

_Copied from original issue: wtchg-kwiatkowski/observatory-web#149_

**Comment by benjeffery** [comment]
_From @leehart on August 1, 2018 9:13_

I have also witnessed this (closing channels) working within the same version, after doing other things, but it consistently breaks from the starting position.

**Comment by leehart** [comment]
Verification of fix.

No error found in the example Genotypes dataset
New tab [tab] > Genome Browser [button] > ADD CHANNELS [button] > [delete channels]

No error found in the example Samples_and_Variants dataset
Start [tab] > Genome Browser [button] > ADD CHANNELS [button] > [delete channels]

NOTE: Since this issue was found with a different dataset (observatory-web), the fix ought to be verified there too.
