### ISSUE TITLE
Property legend shows min->min not min->max

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#1143]
From https://github.com/wtchg-kwiatkowski/observatory-web/issues/193

**Comment by leehart** [comment]
Verification of fix:

No issue found in the example Genotypes dataset
New tab [tab] > Genome Browser [button] > ADD CHANNELS [button] > [add "Variants > Variants" channel] > [channel configuration] > Colour By: Value 1 > [channel information/legend] > [see that the range goes from 0 to 2, rather than 0 to 0]
