### ISSUE TITLE
Table query tool categorical field bugs

### ISSUE THREAD

**Issue by alimanfoo** [cggh/panoptes#389]
Sorry, two bugs in one issue, but seem closely related...

On the new ag1000g instance, go to variants table, click "change filter", select "CHROM" field. "2L" value is automatically selected, but value is not actually set in the query. If I want to choose "2L" I have to change to something else then change back again.

Change value to "2R" then back to "2L" then click "X" to remove the criterion. Now try clicking "ADD CRITERION" again, nothing happens.

**Comment by benjeffery** [comment]
Yep, seen this myself, scheduling for next milestone.

**Comment by leehart** [comment]
The second bug generates an error from panoptes/Deformatter.js line 9, because property is not defined.

  if (property.isBoolean) {
    return _indexOf(['Yes', 'yes', '1', 'true', 'True'], string) !== -1 ? '1' : '0';
  }

Deformatter is called from panoptes/QueryEditor.js, in this case probably from validateOperatorAndValues() circa line 147

My hunch is that the onChange, which triggers containers/QueryPicker.js handleQueryChange(newQuery), might need to do more than change the query state. Either way, QueryEditor is expecting something to exist that is actually undefined, i.e. component.ColName

  validateOperatorAndValues() {
    let {component} = this.props;
    let property = this.tableConfig.propertiesMap[component.ColName];
[...]
  }

**Comment by leehart** [comment]
A fix for the 2nd bug is now piping its way down the pipeline for the 2.0.alpha5 release.

**Comment by leehart** [comment]
It looks like the first bug happens when QueryEditor's handlePropertyChange() triggers QueryPicker's handleQueryChange(newQuery) but the change to the displayed value, which is a consequence of a different property object in render(), is not included in the new query. 

QueryEditor's validateOperatorAndValues() does not change the CompValue in this case, so we still see the value from the previous query in the QueryString, because the query prop hasn't actually changed. (In the Ag1000G example, the unset value in the query was actually the empty string from the previous query for Id. If you give it a non-empty value before switching, then the misbehaviour should be clearer.)

**Comment by leehart** [comment]
Even if the CompValue was changed beforehand, QueryEditor's validateOperatorAndValues() would currently overwrite the value with whatever CompValue is in the state, which would still be the CompValue from the previous query, set before the property was changed.

**Comment by leehart** [comment]
A potential fix for the 1st bug is in the pipe, five by five.
