### ISSUE TITLE
Sidebar should only slide in on first mount - not on every tab switch.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#610]

**Comment by leehart** [comment]
E.g.
Normal behaviour:
Samples & Variants
Start > _left click_ Open a view: Genome Browser
Start > _left click_ Open a table: Variants
The sidebar opens initially, and switching between tabs has no effect on the sidebar state.

Naughty behaviour:
Samples & Variants
Start > _middle click_ Open a view: Genome Browser
Select the Genome Browser tab
See that the sidebar is not open, and the toggle is an arrow (open state) rather than a hamburger.
