### ISSUE TITLE
Genotype browser track picker should sub group columns

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#630]

**Comment by leehart** [comment]
@benjeffery e.g. subgroup numerical tracks to display by table?

Genotypes Example
Start > Genome Browser > Add channels > Variants > Value 1 > Add 1 channel
Value 1 > (settings cog) > Add/remove tracks > Variants > Value 1, Value 2, Value 3, etc.

**Comment by benjeffery** [comment]
Start > Genome Browser > Add channels is cuurently grouped by table, should be table, then column group.

**Comment by leehart** [comment]
Samples & Variants
Start > Genome Browser > Add channels
Click on Variants (14 channels): [Variants, Variant name]
Click on Variants (14 channels): [Variants, Variant name] again
Click on Nucleotides (3 channels): [Nucleotides, Accessibility]
Click on Nucleotides (3 channels): [Nucleotides, Accessibility] again

Below "6 channels to add", items should be grouped:
Variants (4 channels): [Variants, Variant name, Variants, Variant name]
Nucleotides (4 channels): [Nucleotides, Accessibility, Nucleotides, Accessibility]

**Comment by benjeffery** [comment]
Do you mean on the right? I meant on the left. Currently grouping on the left is by table, on AG we have ~150 tracks so it would be good to have table->column group.

**Comment by leehart** [comment]
@benjeffery Third time lucky? :-D

Ag1000G_Selection
Start > Genome Browser > Add channels
Click on Variants (116 channels)

Instead of listing all channels (table columns) in config order, list all "column groups" in config order, where the "column groups" in this example are: Variants: {Properties, Effect, Allele frequencies, Quality, Selection}, as seen in the Filter Editor criterion property selector. Within each column group, list all of the channels (table columns) belonging to each column group, in config order.

E.g.
Variants: {Properties: {Variants, REF, ALT1, ALT2, ALT3, Num_alleles}, Effect: {...}, ...}

**Comment by benjeffery** [comment]
Exactly! :D
