### ISSUE TITLE
Plot categorical colours should use valueColours where specified.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#662]

**Comment by benjeffery** [comment]
Should use `Colours.js:51`

**Comment by leehart** [comment]
Samples & Variants
Start > Table Plotter
- Table: Variants
- Plot Type: Scatter
- Horizontal: Chromosome
- Vertical: Position
- Colour: Extra 1

Currently *attempts* to use propertyColour() from Colours.js, which in this example uses categoryColours()

...but is malfunctioning, i.e. calling `propertyColour(propertyName)` instead of `propertyColour(propertyConfig)`
