### ISSUE TITLE
Reduce map zoom step size if possible

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#725]
Step is too large - particularly at low zoom.
https://github.com/malariagen/panoptes-ag1000g/issues/241

**Comment by leehart** [comment]
Early searches have been encouraging
- Fractional zoom level support was added in Leaflet 1.0 beta, so we should be able to do things like `map.setZoom(12.34)`

**Comment by leehart** [comment]
TIL: you can draw a zoom & centre box on the map by holding down the shift key

**Comment by leehart** [comment]
WRT: https://gist.github.com/croxton/6248586

Overriding the default CRS scale function (replicated below) for tile layers that use 256px square raster tiles causes inappropriate tile placement, perhaps unsurprisingly.

```
    let crs = window.L.extend({}, this.getCRS(), {
      scale: (zoom) => 256 * Math.pow(2, zoom)
    });
```

The ways forward for raster tile layers seems to involve manually pre-generating sets of intermediate zoom level images, along the lines of:
http://stackoverflow.com/questions/13154295/adding-an-extra-zoom-levels-in-leaflet-maps

Or we could look at using vector tiles for base layers, instead of PNG tiles, and somehow configuring custom zoom increments, with anything else (vector or raster) layered on top as usual.
http://leafletjs.com/plugins.html#vector-tiles

I think the OSM raster tiles we're sourcing are pre-rendered by the Mapnik engine... So it might be possible to go "vector-only" with OSM data for our default base layer, e.g. http://mapworks.xyz/

I was hoping to find a way to make Leaflet stretch/interpolate intermediate tiles, like it does with the zoom animation. (Incidentally, zoomAnimation is currently switched off?)

**Comment by leehart** [comment]
Passed to @benjeffery for further discussion/investigation.

**Comment by benjeffery** [comment]
We did this recently for analytics.
