### ISSUE TITLE
Italic fonts become emboldened

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#865]
E.g. Pf60 study template when publications include `<i>` tags

**Comment by leehart** [comment]
This seems to be due to using Roboto, in main.scss

```css
body {
  font-family: 'Roboto', sans-serif;
```

Anything _italic_ in Roboto seems to render as both _italic_ and **bold**, e.g. **_italicbold_**.

A quick test on Samples_and_Variants shows that:
1. If you try to make any word just _italic_ in the `doc/index.html`, using `<i>`, it appears as **_italicbold_**.
2. If you change the font-family in main.scss to something that isn't Roboto, e.g. Arial, then the problem disappears, i.e. all words that should only be _italic_ are only _italic_.

I haven't found anything else in the CSS inspectors to suggest that the **boldness** is leaking in from another style.

Now looking for a way to keep using Roboto without the unwanted side-effects...

**Comment by leehart** [comment]
Actually, I think it's a typo
```
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,700italic' rel='stylesheet' type='text/css'>
```
Maybe should be this (seems to work):
```
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,italic' rel='stylesheet' type='text/css'>
```
