### ISSUE TITLE
Map legends should be sorted alphanumerically

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#945]

**Comment by leehart** [comment]
Samples_and_Variants > Map Composer > {Markers: Sampling sites; Marker colour: Country Code}
See that the legend of the map shows the Country Code values in the sequence [UK, BE, null] instead of [BE, UK, null].

In ascending alphabetical sorting (lexicographical), "B11" would appear before "B2". Whereas, in ascending natural sort order, "B2" should appear before "B11".
