### ISSUE TITLE
Add GeoJSON layer for a table

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#956]
After #955 
Something like:
`<TableGeoJSON table="regions" query="{blah blah}" geoJSONproperty="regionPolygon" colourProperty="" />`

`colourProperty` uses the existing colour allocation routines in `Colours.js/propertyColour`

**Comment by leehart** [comment]
Reminds me of the old Panoptes terminology issue. I would have expected, if we are talking about `tables` here, to be talking about `columns` rather than `properties`. In my lexicon, a `property` refers to an attribute of an object, in programming-speak (and physics-speak), and `field` refers to an input on a form, in web-speak. In Panoptes-speak though, `property` seems synonymous with a table's column. Perhaps the original purpose was to dissociate it from its tabular data source and cement its identity as a programming construct.

**Comment by leehart** [comment]
Closed by PR #961
